# Generated by Django 4.1 on 2023-08-29 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("example_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BarangWishlist",
        ),
    ]
